# Generated by Django 4.2.3 on 2023-11-08 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_like_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate'),
        ),
    ]
